# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.7/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hgranule/Desktop/webserv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hgranule/Desktop/webserv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hgranule/Desktop/webserv/CMakeFiles /Users/hgranule/Desktop/webserv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hgranule/Desktop/webserv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named webserv

# Build rule for target.
webserv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webserv
.PHONY : webserv

# fast build rule for target.
webserv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/build
.PHONY : webserv/fast

#=============================================================================
# Target rules for targets named ft

# Build rule for target.
ft: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ft
.PHONY : ft

# fast build rule for target.
ft/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/build
.PHONY : ft/fast

#=============================================================================
# Target rules for targets named config_parser

# Build rule for target.
config_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 config_parser
.PHONY : config_parser

# fast build rule for target.
config_parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_parser.dir/build.make CMakeFiles/config_parser.dir/build
.PHONY : config_parser/fast

#=============================================================================
# Target rules for targets named http

# Build rule for target.
http: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 http
.PHONY : http

# fast build rule for target.
http/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/build
.PHONY : http/fast

#=============================================================================
# Target rules for targets named cgi

# Build rule for target.
cgi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cgi
.PHONY : cgi

# fast build rule for target.
cgi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgi.dir/build.make CMakeFiles/cgi.dir/build
.PHONY : cgi/fast

#=============================================================================
# Target rules for targets named netlib

# Build rule for target.
netlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 netlib
.PHONY : netlib

# fast build rule for target.
netlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/build
.PHONY : netlib/fast

#=============================================================================
# Target rules for targets named logger

# Build rule for target.
logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logger
.PHONY : logger

# fast build rule for target.
logger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/build
.PHONY : logger/fast

sources/cgi/metavars.o: sources/cgi/metavars.cc.o

.PHONY : sources/cgi/metavars.o

# target to build an object file
sources/cgi/metavars.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgi.dir/build.make CMakeFiles/cgi.dir/sources/cgi/metavars.cc.o
.PHONY : sources/cgi/metavars.cc.o

sources/cgi/metavars.i: sources/cgi/metavars.cc.i

.PHONY : sources/cgi/metavars.i

# target to preprocess a source file
sources/cgi/metavars.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgi.dir/build.make CMakeFiles/cgi.dir/sources/cgi/metavars.cc.i
.PHONY : sources/cgi/metavars.cc.i

sources/cgi/metavars.s: sources/cgi/metavars.cc.s

.PHONY : sources/cgi/metavars.s

# target to generate assembly for a file
sources/cgi/metavars.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgi.dir/build.make CMakeFiles/cgi.dir/sources/cgi/metavars.cc.s
.PHONY : sources/cgi/metavars.cc.s

sources/cgi/response_reader.o: sources/cgi/response_reader.cc.o

.PHONY : sources/cgi/response_reader.o

# target to build an object file
sources/cgi/response_reader.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgi.dir/build.make CMakeFiles/cgi.dir/sources/cgi/response_reader.cc.o
.PHONY : sources/cgi/response_reader.cc.o

sources/cgi/response_reader.i: sources/cgi/response_reader.cc.i

.PHONY : sources/cgi/response_reader.i

# target to preprocess a source file
sources/cgi/response_reader.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgi.dir/build.make CMakeFiles/cgi.dir/sources/cgi/response_reader.cc.i
.PHONY : sources/cgi/response_reader.cc.i

sources/cgi/response_reader.s: sources/cgi/response_reader.cc.s

.PHONY : sources/cgi/response_reader.s

# target to generate assembly for a file
sources/cgi/response_reader.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cgi.dir/build.make CMakeFiles/cgi.dir/sources/cgi/response_reader.cc.s
.PHONY : sources/cgi/response_reader.cc.s

sources/common/file.o: sources/common/file.cc.o

.PHONY : sources/common/file.o

# target to build an object file
sources/common/file.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/sources/common/file.cc.o
.PHONY : sources/common/file.cc.o

sources/common/file.i: sources/common/file.cc.i

.PHONY : sources/common/file.i

# target to preprocess a source file
sources/common/file.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/sources/common/file.cc.i
.PHONY : sources/common/file.cc.i

sources/common/file.s: sources/common/file.cc.s

.PHONY : sources/common/file.s

# target to generate assembly for a file
sources/common/file.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/sources/common/file.cc.s
.PHONY : sources/common/file.cc.s

sources/common/match.o: sources/common/match.cc.o

.PHONY : sources/common/match.o

# target to build an object file
sources/common/match.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/sources/common/match.cc.o
.PHONY : sources/common/match.cc.o

sources/common/match.i: sources/common/match.cc.i

.PHONY : sources/common/match.i

# target to preprocess a source file
sources/common/match.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/sources/common/match.cc.i
.PHONY : sources/common/match.cc.i

sources/common/match.s: sources/common/match.cc.s

.PHONY : sources/common/match.s

# target to generate assembly for a file
sources/common/match.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/sources/common/match.cc.s
.PHONY : sources/common/match.cc.s

sources/common/tokenizer.o: sources/common/tokenizer.cc.o

.PHONY : sources/common/tokenizer.o

# target to build an object file
sources/common/tokenizer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/sources/common/tokenizer.cc.o
.PHONY : sources/common/tokenizer.cc.o

sources/common/tokenizer.i: sources/common/tokenizer.cc.i

.PHONY : sources/common/tokenizer.i

# target to preprocess a source file
sources/common/tokenizer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/sources/common/tokenizer.cc.i
.PHONY : sources/common/tokenizer.cc.i

sources/common/tokenizer.s: sources/common/tokenizer.cc.s

.PHONY : sources/common/tokenizer.s

# target to generate assembly for a file
sources/common/tokenizer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft.dir/build.make CMakeFiles/ft.dir/sources/common/tokenizer.cc.s
.PHONY : sources/common/tokenizer.cc.s

sources/config/config.o: sources/config/config.cc.o

.PHONY : sources/config/config.o

# target to build an object file
sources/config/config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_parser.dir/build.make CMakeFiles/config_parser.dir/sources/config/config.cc.o
.PHONY : sources/config/config.cc.o

sources/config/config.i: sources/config/config.cc.i

.PHONY : sources/config/config.i

# target to preprocess a source file
sources/config/config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_parser.dir/build.make CMakeFiles/config_parser.dir/sources/config/config.cc.i
.PHONY : sources/config/config.cc.i

sources/config/config.s: sources/config/config.cc.s

.PHONY : sources/config/config.s

# target to generate assembly for a file
sources/config/config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/config_parser.dir/build.make CMakeFiles/config_parser.dir/sources/config/config.cc.s
.PHONY : sources/config/config.cc.s

sources/http/headers.o: sources/http/headers.cc.o

.PHONY : sources/http/headers.o

# target to build an object file
sources/http/headers.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/headers.cc.o
.PHONY : sources/http/headers.cc.o

sources/http/headers.i: sources/http/headers.cc.i

.PHONY : sources/http/headers.i

# target to preprocess a source file
sources/http/headers.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/headers.cc.i
.PHONY : sources/http/headers.cc.i

sources/http/headers.s: sources/http/headers.cc.s

.PHONY : sources/http/headers.s

# target to generate assembly for a file
sources/http/headers.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/headers.cc.s
.PHONY : sources/http/headers.cc.s

sources/http/http.o: sources/http/http.cc.o

.PHONY : sources/http/http.o

# target to build an object file
sources/http/http.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/http.cc.o
.PHONY : sources/http/http.cc.o

sources/http/http.i: sources/http/http.cc.i

.PHONY : sources/http/http.i

# target to preprocess a source file
sources/http/http.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/http.cc.i
.PHONY : sources/http/http.cc.i

sources/http/http.s: sources/http/http.cc.s

.PHONY : sources/http/http.s

# target to generate assembly for a file
sources/http/http.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/http.cc.s
.PHONY : sources/http/http.cc.s

sources/http/mime.o: sources/http/mime.cc.o

.PHONY : sources/http/mime.o

# target to build an object file
sources/http/mime.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/mime.cc.o
.PHONY : sources/http/mime.cc.o

sources/http/mime.i: sources/http/mime.cc.i

.PHONY : sources/http/mime.i

# target to preprocess a source file
sources/http/mime.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/mime.cc.i
.PHONY : sources/http/mime.cc.i

sources/http/mime.s: sources/http/mime.cc.s

.PHONY : sources/http/mime.s

# target to generate assembly for a file
sources/http/mime.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/mime.cc.s
.PHONY : sources/http/mime.cc.s

sources/http/reader_common.o: sources/http/reader_common.cc.o

.PHONY : sources/http/reader_common.o

# target to build an object file
sources/http/reader_common.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/reader_common.cc.o
.PHONY : sources/http/reader_common.cc.o

sources/http/reader_common.i: sources/http/reader_common.cc.i

.PHONY : sources/http/reader_common.i

# target to preprocess a source file
sources/http/reader_common.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/reader_common.cc.i
.PHONY : sources/http/reader_common.cc.i

sources/http/reader_common.s: sources/http/reader_common.cc.s

.PHONY : sources/http/reader_common.s

# target to generate assembly for a file
sources/http/reader_common.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/reader_common.cc.s
.PHONY : sources/http/reader_common.cc.s

sources/http/reader_request.o: sources/http/reader_request.cc.o

.PHONY : sources/http/reader_request.o

# target to build an object file
sources/http/reader_request.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/reader_request.cc.o
.PHONY : sources/http/reader_request.cc.o

sources/http/reader_request.i: sources/http/reader_request.cc.i

.PHONY : sources/http/reader_request.i

# target to preprocess a source file
sources/http/reader_request.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/reader_request.cc.i
.PHONY : sources/http/reader_request.cc.i

sources/http/reader_request.s: sources/http/reader_request.cc.s

.PHONY : sources/http/reader_request.s

# target to generate assembly for a file
sources/http/reader_request.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/reader_request.cc.s
.PHONY : sources/http/reader_request.cc.s

sources/http/reader_response.o: sources/http/reader_response.cc.o

.PHONY : sources/http/reader_response.o

# target to build an object file
sources/http/reader_response.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/reader_response.cc.o
.PHONY : sources/http/reader_response.cc.o

sources/http/reader_response.i: sources/http/reader_response.cc.i

.PHONY : sources/http/reader_response.i

# target to preprocess a source file
sources/http/reader_response.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/reader_response.cc.i
.PHONY : sources/http/reader_response.cc.i

sources/http/reader_response.s: sources/http/reader_response.cc.s

.PHONY : sources/http/reader_response.s

# target to generate assembly for a file
sources/http/reader_response.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/reader_response.cc.s
.PHONY : sources/http/reader_response.cc.s

sources/http/uri.o: sources/http/uri.cc.o

.PHONY : sources/http/uri.o

# target to build an object file
sources/http/uri.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/uri.cc.o
.PHONY : sources/http/uri.cc.o

sources/http/uri.i: sources/http/uri.cc.i

.PHONY : sources/http/uri.i

# target to preprocess a source file
sources/http/uri.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/uri.cc.i
.PHONY : sources/http/uri.cc.i

sources/http/uri.s: sources/http/uri.cc.s

.PHONY : sources/http/uri.s

# target to generate assembly for a file
sources/http/uri.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/uri.cc.s
.PHONY : sources/http/uri.cc.s

sources/http/writer.o: sources/http/writer.cc.o

.PHONY : sources/http/writer.o

# target to build an object file
sources/http/writer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/writer.cc.o
.PHONY : sources/http/writer.cc.o

sources/http/writer.i: sources/http/writer.cc.i

.PHONY : sources/http/writer.i

# target to preprocess a source file
sources/http/writer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/writer.cc.i
.PHONY : sources/http/writer.cc.i

sources/http/writer.s: sources/http/writer.cc.s

.PHONY : sources/http/writer.s

# target to generate assembly for a file
sources/http/writer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/sources/http/writer.cc.s
.PHONY : sources/http/writer.cc.s

sources/logger/logger.o: sources/logger/logger.cc.o

.PHONY : sources/logger/logger.o

# target to build an object file
sources/logger/logger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/sources/logger/logger.cc.o
.PHONY : sources/logger/logger.cc.o

sources/logger/logger.i: sources/logger/logger.cc.i

.PHONY : sources/logger/logger.i

# target to preprocess a source file
sources/logger/logger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/sources/logger/logger.cc.i
.PHONY : sources/logger/logger.cc.i

sources/logger/logger.s: sources/logger/logger.cc.s

.PHONY : sources/logger/logger.s

# target to generate assembly for a file
sources/logger/logger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/sources/logger/logger.cc.s
.PHONY : sources/logger/logger.cc.s

sources/main.o: sources/main.cc.o

.PHONY : sources/main.o

# target to build an object file
sources/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/sources/main.cc.o
.PHONY : sources/main.cc.o

sources/main.i: sources/main.cc.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/sources/main.cc.i
.PHONY : sources/main.cc.i

sources/main.s: sources/main.cc.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/sources/main.cc.s
.PHONY : sources/main.cc.s

sources/netlib/event/loop.o: sources/netlib/event/loop.cc.o

.PHONY : sources/netlib/event/loop.o

# target to build an object file
sources/netlib/event/loop.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/event/loop.cc.o
.PHONY : sources/netlib/event/loop.cc.o

sources/netlib/event/loop.i: sources/netlib/event/loop.cc.i

.PHONY : sources/netlib/event/loop.i

# target to preprocess a source file
sources/netlib/event/loop.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/event/loop.cc.i
.PHONY : sources/netlib/event/loop.cc.i

sources/netlib/event/loop.s: sources/netlib/event/loop.cc.s

.PHONY : sources/netlib/event/loop.s

# target to generate assembly for a file
sources/netlib/event/loop.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/event/loop.cc.s
.PHONY : sources/netlib/event/loop.cc.s

sources/netlib/io/file.o: sources/netlib/io/file.cc.o

.PHONY : sources/netlib/io/file.o

# target to build an object file
sources/netlib/io/file.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/io/file.cc.o
.PHONY : sources/netlib/io/file.cc.o

sources/netlib/io/file.i: sources/netlib/io/file.cc.i

.PHONY : sources/netlib/io/file.i

# target to preprocess a source file
sources/netlib/io/file.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/io/file.cc.i
.PHONY : sources/netlib/io/file.cc.i

sources/netlib/io/file.s: sources/netlib/io/file.cc.s

.PHONY : sources/netlib/io/file.s

# target to generate assembly for a file
sources/netlib/io/file.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/io/file.cc.s
.PHONY : sources/netlib/io/file.cc.s

sources/netlib/io/poller.o: sources/netlib/io/poller.cc.o

.PHONY : sources/netlib/io/poller.o

# target to build an object file
sources/netlib/io/poller.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/io/poller.cc.o
.PHONY : sources/netlib/io/poller.cc.o

sources/netlib/io/poller.i: sources/netlib/io/poller.cc.i

.PHONY : sources/netlib/io/poller.i

# target to preprocess a source file
sources/netlib/io/poller.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/io/poller.cc.i
.PHONY : sources/netlib/io/poller.cc.i

sources/netlib/io/poller.s: sources/netlib/io/poller.cc.s

.PHONY : sources/netlib/io/poller.s

# target to generate assembly for a file
sources/netlib/io/poller.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/io/poller.cc.s
.PHONY : sources/netlib/io/poller.cc.s

sources/netlib/io/socket.o: sources/netlib/io/socket.cc.o

.PHONY : sources/netlib/io/socket.o

# target to build an object file
sources/netlib/io/socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/io/socket.cc.o
.PHONY : sources/netlib/io/socket.cc.o

sources/netlib/io/socket.i: sources/netlib/io/socket.cc.i

.PHONY : sources/netlib/io/socket.i

# target to preprocess a source file
sources/netlib/io/socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/io/socket.cc.i
.PHONY : sources/netlib/io/socket.cc.i

sources/netlib/io/socket.s: sources/netlib/io/socket.cc.s

.PHONY : sources/netlib/io/socket.s

# target to generate assembly for a file
sources/netlib/io/socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/io/socket.cc.s
.PHONY : sources/netlib/io/socket.cc.s

sources/netlib/webserver/webserver.o: sources/netlib/webserver/webserver.cc.o

.PHONY : sources/netlib/webserver/webserver.o

# target to build an object file
sources/netlib/webserver/webserver.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver.cc.o
.PHONY : sources/netlib/webserver/webserver.cc.o

sources/netlib/webserver/webserver.i: sources/netlib/webserver/webserver.cc.i

.PHONY : sources/netlib/webserver/webserver.i

# target to preprocess a source file
sources/netlib/webserver/webserver.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver.cc.i
.PHONY : sources/netlib/webserver/webserver.cc.i

sources/netlib/webserver/webserver.s: sources/netlib/webserver/webserver.cc.s

.PHONY : sources/netlib/webserver/webserver.s

# target to generate assembly for a file
sources/netlib/webserver/webserver.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver.cc.s
.PHONY : sources/netlib/webserver/webserver.cc.s

sources/netlib/webserver/webserver_cgi.o: sources/netlib/webserver/webserver_cgi.cc.o

.PHONY : sources/netlib/webserver/webserver_cgi.o

# target to build an object file
sources/netlib/webserver/webserver_cgi.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_cgi.cc.o
.PHONY : sources/netlib/webserver/webserver_cgi.cc.o

sources/netlib/webserver/webserver_cgi.i: sources/netlib/webserver/webserver_cgi.cc.i

.PHONY : sources/netlib/webserver/webserver_cgi.i

# target to preprocess a source file
sources/netlib/webserver/webserver_cgi.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_cgi.cc.i
.PHONY : sources/netlib/webserver/webserver_cgi.cc.i

sources/netlib/webserver/webserver_cgi.s: sources/netlib/webserver/webserver_cgi.cc.s

.PHONY : sources/netlib/webserver/webserver_cgi.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_cgi.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_cgi.cc.s
.PHONY : sources/netlib/webserver/webserver_cgi.cc.s

sources/netlib/webserver/webserver_err.o: sources/netlib/webserver/webserver_err.cc.o

.PHONY : sources/netlib/webserver/webserver_err.o

# target to build an object file
sources/netlib/webserver/webserver_err.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_err.cc.o
.PHONY : sources/netlib/webserver/webserver_err.cc.o

sources/netlib/webserver/webserver_err.i: sources/netlib/webserver/webserver_err.cc.i

.PHONY : sources/netlib/webserver/webserver_err.i

# target to preprocess a source file
sources/netlib/webserver/webserver_err.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_err.cc.i
.PHONY : sources/netlib/webserver/webserver_err.cc.i

sources/netlib/webserver/webserver_err.s: sources/netlib/webserver/webserver_err.cc.s

.PHONY : sources/netlib/webserver/webserver_err.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_err.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_err.cc.s
.PHONY : sources/netlib/webserver/webserver_err.cc.s

sources/netlib/webserver/webserver_http.o: sources/netlib/webserver/webserver_http.cc.o

.PHONY : sources/netlib/webserver/webserver_http.o

# target to build an object file
sources/netlib/webserver/webserver_http.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_http.cc.o
.PHONY : sources/netlib/webserver/webserver_http.cc.o

sources/netlib/webserver/webserver_http.i: sources/netlib/webserver/webserver_http.cc.i

.PHONY : sources/netlib/webserver/webserver_http.i

# target to preprocess a source file
sources/netlib/webserver/webserver_http.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_http.cc.i
.PHONY : sources/netlib/webserver/webserver_http.cc.i

sources/netlib/webserver/webserver_http.s: sources/netlib/webserver/webserver_http.cc.s

.PHONY : sources/netlib/webserver/webserver_http.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_http.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_http.cc.s
.PHONY : sources/netlib/webserver/webserver_http.cc.s

sources/netlib/webserver/webserver_listener_event.o: sources/netlib/webserver/webserver_listener_event.cc.o

.PHONY : sources/netlib/webserver/webserver_listener_event.o

# target to build an object file
sources/netlib/webserver/webserver_listener_event.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_listener_event.cc.o
.PHONY : sources/netlib/webserver/webserver_listener_event.cc.o

sources/netlib/webserver/webserver_listener_event.i: sources/netlib/webserver/webserver_listener_event.cc.i

.PHONY : sources/netlib/webserver/webserver_listener_event.i

# target to preprocess a source file
sources/netlib/webserver/webserver_listener_event.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_listener_event.cc.i
.PHONY : sources/netlib/webserver/webserver_listener_event.cc.i

sources/netlib/webserver/webserver_listener_event.s: sources/netlib/webserver/webserver_listener_event.cc.s

.PHONY : sources/netlib/webserver/webserver_listener_event.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_listener_event.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_listener_event.cc.s
.PHONY : sources/netlib/webserver/webserver_listener_event.cc.s

sources/netlib/webserver/webserver_listing.o: sources/netlib/webserver/webserver_listing.cc.o

.PHONY : sources/netlib/webserver/webserver_listing.o

# target to build an object file
sources/netlib/webserver/webserver_listing.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_listing.cc.o
.PHONY : sources/netlib/webserver/webserver_listing.cc.o

sources/netlib/webserver/webserver_listing.i: sources/netlib/webserver/webserver_listing.cc.i

.PHONY : sources/netlib/webserver/webserver_listing.i

# target to preprocess a source file
sources/netlib/webserver/webserver_listing.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_listing.cc.i
.PHONY : sources/netlib/webserver/webserver_listing.cc.i

sources/netlib/webserver/webserver_listing.s: sources/netlib/webserver/webserver_listing.cc.s

.PHONY : sources/netlib/webserver/webserver_listing.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_listing.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_listing.cc.s
.PHONY : sources/netlib/webserver/webserver_listing.cc.s

sources/netlib/webserver/webserver_poll.o: sources/netlib/webserver/webserver_poll.cc.o

.PHONY : sources/netlib/webserver/webserver_poll.o

# target to build an object file
sources/netlib/webserver/webserver_poll.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_poll.cc.o
.PHONY : sources/netlib/webserver/webserver_poll.cc.o

sources/netlib/webserver/webserver_poll.i: sources/netlib/webserver/webserver_poll.cc.i

.PHONY : sources/netlib/webserver/webserver_poll.i

# target to preprocess a source file
sources/netlib/webserver/webserver_poll.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_poll.cc.i
.PHONY : sources/netlib/webserver/webserver_poll.cc.i

sources/netlib/webserver/webserver_poll.s: sources/netlib/webserver/webserver_poll.cc.s

.PHONY : sources/netlib/webserver/webserver_poll.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_poll.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_poll.cc.s
.PHONY : sources/netlib/webserver/webserver_poll.cc.s

sources/netlib/webserver/webserver_sessions.o: sources/netlib/webserver/webserver_sessions.cc.o

.PHONY : sources/netlib/webserver/webserver_sessions.o

# target to build an object file
sources/netlib/webserver/webserver_sessions.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_sessions.cc.o
.PHONY : sources/netlib/webserver/webserver_sessions.cc.o

sources/netlib/webserver/webserver_sessions.i: sources/netlib/webserver/webserver_sessions.cc.i

.PHONY : sources/netlib/webserver/webserver_sessions.i

# target to preprocess a source file
sources/netlib/webserver/webserver_sessions.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_sessions.cc.i
.PHONY : sources/netlib/webserver/webserver_sessions.cc.i

sources/netlib/webserver/webserver_sessions.s: sources/netlib/webserver/webserver_sessions.cc.s

.PHONY : sources/netlib/webserver/webserver_sessions.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_sessions.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_sessions.cc.s
.PHONY : sources/netlib/webserver/webserver_sessions.cc.s

sources/netlib/webserver/webserver_static.o: sources/netlib/webserver/webserver_static.cc.o

.PHONY : sources/netlib/webserver/webserver_static.o

# target to build an object file
sources/netlib/webserver/webserver_static.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_static.cc.o
.PHONY : sources/netlib/webserver/webserver_static.cc.o

sources/netlib/webserver/webserver_static.i: sources/netlib/webserver/webserver_static.cc.i

.PHONY : sources/netlib/webserver/webserver_static.i

# target to preprocess a source file
sources/netlib/webserver/webserver_static.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_static.cc.i
.PHONY : sources/netlib/webserver/webserver_static.cc.i

sources/netlib/webserver/webserver_static.s: sources/netlib/webserver/webserver_static.cc.s

.PHONY : sources/netlib/webserver/webserver_static.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_static.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_static.cc.s
.PHONY : sources/netlib/webserver/webserver_static.cc.s

sources/netlib/webserver/webserver_timeout.o: sources/netlib/webserver/webserver_timeout.cc.o

.PHONY : sources/netlib/webserver/webserver_timeout.o

# target to build an object file
sources/netlib/webserver/webserver_timeout.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_timeout.cc.o
.PHONY : sources/netlib/webserver/webserver_timeout.cc.o

sources/netlib/webserver/webserver_timeout.i: sources/netlib/webserver/webserver_timeout.cc.i

.PHONY : sources/netlib/webserver/webserver_timeout.i

# target to preprocess a source file
sources/netlib/webserver/webserver_timeout.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_timeout.cc.i
.PHONY : sources/netlib/webserver/webserver_timeout.cc.i

sources/netlib/webserver/webserver_timeout.s: sources/netlib/webserver/webserver_timeout.cc.s

.PHONY : sources/netlib/webserver/webserver_timeout.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_timeout.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_timeout.cc.s
.PHONY : sources/netlib/webserver/webserver_timeout.cc.s

sources/netlib/webserver/webserver_upload.o: sources/netlib/webserver/webserver_upload.cc.o

.PHONY : sources/netlib/webserver/webserver_upload.o

# target to build an object file
sources/netlib/webserver/webserver_upload.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_upload.cc.o
.PHONY : sources/netlib/webserver/webserver_upload.cc.o

sources/netlib/webserver/webserver_upload.i: sources/netlib/webserver/webserver_upload.cc.i

.PHONY : sources/netlib/webserver/webserver_upload.i

# target to preprocess a source file
sources/netlib/webserver/webserver_upload.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_upload.cc.i
.PHONY : sources/netlib/webserver/webserver_upload.cc.i

sources/netlib/webserver/webserver_upload.s: sources/netlib/webserver/webserver_upload.cc.s

.PHONY : sources/netlib/webserver/webserver_upload.s

# target to generate assembly for a file
sources/netlib/webserver/webserver_upload.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netlib.dir/build.make CMakeFiles/netlib.dir/sources/netlib/webserver/webserver_upload.cc.s
.PHONY : sources/netlib/webserver/webserver_upload.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cgi"
	@echo "... config_parser"
	@echo "... ft"
	@echo "... http"
	@echo "... logger"
	@echo "... netlib"
	@echo "... webserv"
	@echo "... sources/cgi/metavars.o"
	@echo "... sources/cgi/metavars.i"
	@echo "... sources/cgi/metavars.s"
	@echo "... sources/cgi/response_reader.o"
	@echo "... sources/cgi/response_reader.i"
	@echo "... sources/cgi/response_reader.s"
	@echo "... sources/common/file.o"
	@echo "... sources/common/file.i"
	@echo "... sources/common/file.s"
	@echo "... sources/common/match.o"
	@echo "... sources/common/match.i"
	@echo "... sources/common/match.s"
	@echo "... sources/common/tokenizer.o"
	@echo "... sources/common/tokenizer.i"
	@echo "... sources/common/tokenizer.s"
	@echo "... sources/config/config.o"
	@echo "... sources/config/config.i"
	@echo "... sources/config/config.s"
	@echo "... sources/http/headers.o"
	@echo "... sources/http/headers.i"
	@echo "... sources/http/headers.s"
	@echo "... sources/http/http.o"
	@echo "... sources/http/http.i"
	@echo "... sources/http/http.s"
	@echo "... sources/http/mime.o"
	@echo "... sources/http/mime.i"
	@echo "... sources/http/mime.s"
	@echo "... sources/http/reader_common.o"
	@echo "... sources/http/reader_common.i"
	@echo "... sources/http/reader_common.s"
	@echo "... sources/http/reader_request.o"
	@echo "... sources/http/reader_request.i"
	@echo "... sources/http/reader_request.s"
	@echo "... sources/http/reader_response.o"
	@echo "... sources/http/reader_response.i"
	@echo "... sources/http/reader_response.s"
	@echo "... sources/http/uri.o"
	@echo "... sources/http/uri.i"
	@echo "... sources/http/uri.s"
	@echo "... sources/http/writer.o"
	@echo "... sources/http/writer.i"
	@echo "... sources/http/writer.s"
	@echo "... sources/logger/logger.o"
	@echo "... sources/logger/logger.i"
	@echo "... sources/logger/logger.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/netlib/event/loop.o"
	@echo "... sources/netlib/event/loop.i"
	@echo "... sources/netlib/event/loop.s"
	@echo "... sources/netlib/io/file.o"
	@echo "... sources/netlib/io/file.i"
	@echo "... sources/netlib/io/file.s"
	@echo "... sources/netlib/io/poller.o"
	@echo "... sources/netlib/io/poller.i"
	@echo "... sources/netlib/io/poller.s"
	@echo "... sources/netlib/io/socket.o"
	@echo "... sources/netlib/io/socket.i"
	@echo "... sources/netlib/io/socket.s"
	@echo "... sources/netlib/webserver/webserver.o"
	@echo "... sources/netlib/webserver/webserver.i"
	@echo "... sources/netlib/webserver/webserver.s"
	@echo "... sources/netlib/webserver/webserver_cgi.o"
	@echo "... sources/netlib/webserver/webserver_cgi.i"
	@echo "... sources/netlib/webserver/webserver_cgi.s"
	@echo "... sources/netlib/webserver/webserver_err.o"
	@echo "... sources/netlib/webserver/webserver_err.i"
	@echo "... sources/netlib/webserver/webserver_err.s"
	@echo "... sources/netlib/webserver/webserver_http.o"
	@echo "... sources/netlib/webserver/webserver_http.i"
	@echo "... sources/netlib/webserver/webserver_http.s"
	@echo "... sources/netlib/webserver/webserver_listener_event.o"
	@echo "... sources/netlib/webserver/webserver_listener_event.i"
	@echo "... sources/netlib/webserver/webserver_listener_event.s"
	@echo "... sources/netlib/webserver/webserver_listing.o"
	@echo "... sources/netlib/webserver/webserver_listing.i"
	@echo "... sources/netlib/webserver/webserver_listing.s"
	@echo "... sources/netlib/webserver/webserver_poll.o"
	@echo "... sources/netlib/webserver/webserver_poll.i"
	@echo "... sources/netlib/webserver/webserver_poll.s"
	@echo "... sources/netlib/webserver/webserver_sessions.o"
	@echo "... sources/netlib/webserver/webserver_sessions.i"
	@echo "... sources/netlib/webserver/webserver_sessions.s"
	@echo "... sources/netlib/webserver/webserver_static.o"
	@echo "... sources/netlib/webserver/webserver_static.i"
	@echo "... sources/netlib/webserver/webserver_static.s"
	@echo "... sources/netlib/webserver/webserver_timeout.o"
	@echo "... sources/netlib/webserver/webserver_timeout.i"
	@echo "... sources/netlib/webserver/webserver_timeout.s"
	@echo "... sources/netlib/webserver/webserver_upload.o"
	@echo "... sources/netlib/webserver/webserver_upload.i"
	@echo "... sources/netlib/webserver/webserver_upload.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

